" =============================================================================
" PLUGINS
" =============================================================================

set nocompatible
filetype off

" Disable netrw
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

call plug#begin('~/.vim/plugged')

" Writing / markup
Plug 'vim-latex/vim-latex'
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'

" Notebooks
Plug 'aaren/notedown'
Plug 'szymonmaszke/vimpyter'
Plug 'ivanov/vim-ipython'

" Language support
Plug 'jalvesaq/Nvim-R'
Plug 'nvie/vim-flake8'
Plug 'davidhalter/jedi-vim'

" R execution
Plug 'jpalardy/vim-slime'

" Navigation / UI
Plug 'tpope/vim-surround'
Plug 'christoomey/vim-tmux-navigator'
Plug 'voldikss/vim-floaterm'
Plug 'morhetz/gruvbox'

" FZF
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Colour scheme
Plug 'dracula/vim', { 'name': 'dracula' }

call plug#end()

filetype plugin indent on


" =============================================================================
" APPEARANCE
" =============================================================================

set termguicolors
set background=dark
set number
set linebreak
syntax on
set cc=81
set showtabline=2

" set theme to match
colorscheme dracula
hi Normal guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE
hi mkdBlockquote guibg=NONE ctermbg=NONE

" Cursor shape per mode (1=blink block, 2=solid block, 5=blink bar, 6=solid bar)
let &t_SI .= "\e[5 q"   " Insert  → blinking bar
let &t_SR .= "\e[4 q"   " Replace → solid underscore
let &t_EI .= "\e[1 q"   " Normal  → blinking block


" =============================================================================
" EDITOR BEHAVIOUR
" =============================================================================

" Indentation
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set shiftround
set autoindent

" Text width
set textwidth=79

" Splits open to the right and below
set splitright
set splitbelow

" Open all folds by default
set foldlevelstart=99

" LaTeX
set shellslash
let g:tex_flavor = 'latex'


" =============================================================================
" FILE EXPLORER (vim-floaterm + ranger)
" =============================================================================

" Open ranger in a float sized and positioned to the current split
command! Ex FloatermNew --wintype=vsplit --position=belowright --opener=edit ranger
command! Sex  split | FloatermNew --wintype=vsplit --position=belowright --height=0.99 --width=0.5 --opener=edit ranger
command! Vex vsplit | FloatermNew --wintype=vsplit --position=belowright --height=0.99 --width=0.5 --opener=edit ranger

nnoremap <leader>x :Ex<CR>
nnoremap <leader>c :Sex<CR>
nnoremap <leader>v :Vex<CR>

" =============================================================================
" PLUGIN SETTINGS
" =============================================================================

" vim-markdown: disable auto-formatting in lists
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_auto_insert_bullets = 0

" vimpyter: notebook keymaps
autocmd FileType ipynb nmap <silent><leader>b :VimpyterInsertPythonBlock<CR>
autocmd FileType ipynb nmap <silent><leader>j :VimpyterStartJupyter<CR>
autocmd FileType ipynb nmap <silent><leader>n :VimpyterStartNteract<CR>


" =============================================================================
" KEYMAPS
" =============================================================================

" Clipboard
noremap cpy "*y
noremap cpp "*p
noremap cpx "*d

" Copy file path to clipboard
nnoremap <leader>yp :! realpath % \| pbcopy<CR>

" Fuzzy-search open buffers
nnoremap <leader>bb :Buffers<CR>

" Remove trailing whitespace
nnoremap <leader>el :%s/\s\+$//<CR>

" Insert filename as title (capitalised)
nnoremap <leader>f :call append(0, '# ' . substitute(expand('%:t:r'), '^.', '\U&', '')) \| normal! G<CR>

" Insert parent directory name as title (capitalised)
nnoremap <leader>d :call append(0, '# ' . substitute(expand('%:p:h:t'), '^.', '\U&', '')) \| normal! G<CR>

" Fix markdown line breaks (adds trailing '  ' before list items)
nnoremap <leader>md :call AddMarkdownBreaks()<CR>

" Window resize shortcut
command! Vres vertical resize 80

" Insert date
nnoremap <leader>td a## <C-R>=strftime('%Y-%m-%d')<CR><Esc>

" Insert checklists
nnoremap <leader>ex :s/^\(\s*\)\%(-\s\+\[[ x]\]\s*\|-\s\+\)\?/\1- [ ] /<CR>
nnoremap <leader>fx :s/^\(\s*\)\%(-\s\+\[[ x]\]\s*\|-\s\+\)\?/\1- [x] /<CR>
- [ ] soemthing text here 

" Prevent _ reassign in R files
let R_assign = 0

" vim-slime: send code to a tmux pane (radian) instead of screen/vim-terminal
let g:slime_target = "tmux"
let g:slime_bracketed_paste = 1     " avoids R auto-indent mangling multi-line sends
let g:slime_dont_ask_default = 1    " reuse the pane below instead of prompting every send
let g:slime_default_config = {"socket_name": get(split($TMUX, ","), 0, "default"), "target_pane": "{last}"}

" vim-slime: send the ``` chunk under the cursor (quarto/rmarkdown code blocks
" double as slime "cells" since both the opening and closing fence match this
" delimiter, so send_cell() lands on exactly the lines between them)
autocmd BufNewFile,BufRead *.qmd,*.Rmd,*.rmd let b:slime_cell_delimiter = '^```'
nmap <leader>sc <Plug>SlimeSendCell

" vim-slime: send only the code inside ``` fences within a visual selection
" spanning prose + multiple chunks (e.g. selecting several headed sections)
xnoremap <leader>sc :call SlimeSendChunksInRange()<CR>

" =============================================================================
" FUNCTIONS
" =============================================================================

" Strip prose and fence lines from a range, keeping only code inside ``` blocks,
" then send the result to the slime target (used by the visual <leader>sc map)
function! SlimeSendChunksInRange() range
    let in_chunk = 0
    let out = []
    for l in getline(a:firstline, a:lastline)
        if l =~# '^```'
            let in_chunk = !in_chunk
        elseif in_chunk
            call add(out, l)
        endif
    endfor
    if !empty(out)
        call slime#send(join(out, "\n") . "\n")
    endif
    call cursor(line("'>"), col("'>"))
endfunction

" Add '  ' to end of lines that precede a list item, for correct MD rendering
function! AddMarkdownBreaks()
    normal! gg
    while line('.') < line('$')
        let lnum = line('.') + 1
        let txt = getline(lnum)
        if txt =~# '^\s*-'
            call setline('.', getline('.') . '  ')
        endif
        normal! j
    endwhile
endfunction


